### ISSUE TITLE
Everyone's Best Friend (Dogmeat and Companion At Same Time - No Console - No Hack)

### ISSUE THREAD

**Issue by Nymano641** [Nymano641/fallen-society#53]
Maybe a good addition.

**Comment by Nymano641** [comment]
Seems buggy, scrapped

**Comment by AliveStenka** [comment]
Of all the mods about multiple companions, Liga of my companions feels like the best
https://www.nexusmods.com/fallout4/mods/25699

**Comment by Nymano641** [comment]
yeah but again, 16 companions breaks the balance to hell^^ I have to think about it^^ Thanks anyway =)
